# @package _global_
config:
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 5
      topk_values: [1, 5]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res4", ["AdaptiveAvgPool2d", [[2, 1]]]],
        ["res4", ["AdaptiveAvgPool2d", [[1, 2]]]],

        ["res5", ["AdaptiveAvgPool2d", [[2, 1]]]],
        ["res5", ["AdaptiveAvgPool2d", [[1, 2]]]],

        ["avgpool", ["Identity", []]],
      ]
    TRUNK:
      NAME: regnet
      REGNET:   # params (10^6): 2482.8811 #FLOPs (10^9): 391.9545 #activations (10^6): 127.9504
        depth: 31
        w_0: 736
        w_a: 250.83
        w_m: 2.57
        group_width: 430
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 4730, "dims": [9460, 1000]}],
        ["eval_mlp", {"in_channels": 4730, "dims": [9460, 1000]}],

        ["eval_mlp", {"in_channels": 12470, "dims": [24940, 1000]}],
        ["eval_mlp", {"in_channels": 12470, "dims": [24940, 1000]}],

        ["eval_mlp", {"in_channels": 12470, "dims": [12470, 1000]}],
      ]
