# @package _global_
config:
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 5
      topk_values: [1, 5]
  MODEL:
    FEATURE_EVAL_SETTINGS:
      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
        ["res4", ["AdaptiveAvgPool2d", [[2, 1]]]],
        ["res4", ["AdaptiveAvgPool2d", [[1, 2]]]],

        ["res5", ["AdaptiveAvgPool2d", [[2, 1]]]],
        ["res5", ["AdaptiveAvgPool2d", [[1, 2]]]],

        ["avgpool", ["Identity", []]],
        # ["avgpool", ["Identity", []]],
      ]
    TRUNK:
      NAME: regnet
      REGNET:   # params (10^6): 2483.6649 #FLOPs (10^9): 478.7452 #activations (10^6): 139.7843
        depth: 27
        w_0: 832
        w_a: 300.83
        w_m: 2.55
        group_width: 540
    HEAD:
      PARAMS: [
        ["eval_mlp", {"in_channels": 5400, "dims": [10800, 1000]}],
        ["eval_mlp", {"in_channels": 5400, "dims": [10800, 1000]}],

        ["eval_mlp", {"in_channels": 14040, "dims": [28080, 1000]}],
        ["eval_mlp", {"in_channels": 14040, "dims": [28080, 1000]}],

        ["eval_mlp", {"in_channels": 14040, "dims": [14040, 1000]}],
      ]
